services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1522:1521"
      - "5501:5500"
    environment:
      - ORACLE_PWD=theintern
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume_data:/data

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

volumes:
  oracle-data:
  redis_volume_data:
  redis_insight_volume_data:
