spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/FREEPDB1
    username: travelteamsolutions
    password: 1
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

  mail:
    host: localhost
    port: 1025
    username: nqtrang
    password: nqtrang
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 356926343838-d1ek2d8ek4pukn2mg7rfvv6buv7u0b72.apps.googleusercontent.com
            client-secret: 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

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms

application:
  security:
    jwt:
      secret-key: QWxhZGRpbjpvcGVuIHNlc2FtZSBzGVuIHNlc2FtZSBzYW1wbQWxhZGRpbjpvGUgdGV4dA==
      expiration: 864000

  mailing:
    not_reply_email: donotreply@teamsolutions.com
    contact: contact@travelteamsolutions.com
    frontend:
      activation_url: http://localhost:8080/api/v1/auth/activate-account

  redis:
    token:
      expiration: 86400

  provider:
    sms:
      default: twilio
      outgoing_number: +12525504206
      twilio:
        name: twilio
        auth_token: 61e3cb5b860cf768134591e355f49431
        account_sid: AC2abc6671bea8d335d19f674920aa794c

    flight-api:
      default: datacom
      datacom:
        name: "datacom"
        endpoint: "http://localhost:3000"
        private-key: "datacomkey"
        api-account: "datacomapiaccount"
        api-password: "datacomapipassword"
        currency: "VND"
        language: "vi"
        ip-address: "10.0.0.1"
      aviationstack:
        name: aviationstack
        endpoint: https://api.aviationstack.com/v1/
        access-key: d3c2399140f42d6f8300db8b7927098b

  frontend:
    url: "http://localhost:4200"
    oauth-redirect-url: "http://localhost:4200/oauth-redirect"

management:
  endpoints:
    web:
      exposure:
        include: "metrics"
  metrics:
    enable:
      all: true


server:
  port: 9090