spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/FREEPDB1
    username: travelteamsolutions
    password: 1
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: localhost
    port: 1025
    username: nqtrang
    password: nqtrang
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: QWxhZGRpbjpvcGVuIHNlc2FtZSBzGVuIHNlc2FtZSBzYW1wbQWxhZGRpbjpvGUgdGV4dA==
      expiration: 8640000

  mailing:
    not_reply_email: donotreply@teamsolutions.com
    frontend:
      activation_url: http://localhost:4200

server:
  port: 8088
